# Generated by Django 4.2.16 on 2024-10-31 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_id", models.CharField(max_length=255, unique=True)),
                ("username", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
